name: Run Script

on:
  pull_request:
    branches:
      - main
      - master
      - release*
      - develop

jobs:
  image-scan:
    name: image-scan-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: running script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import re 
            regex = r"([A-Za-z]{2,6}-[0-9]{1,6})"
            listOfTicketsFromBranchName = re.findall(regex, "${{ steps.extract_branch.outputs.branch }}")
            listOfTicketsFromPRTitle = re.findall(regex, "${{ github.event.pull_request.title }}")
            listOfTickets = listOfTicketsFromBranchName + listOfTicketsFromPRTitle

            for item in listOfTickets:
              print(item)