name: Run Script

on:
  push:

jobs:
  image-scan:
    name: image-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: running script
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import re 
            regex = r"([A-Za-z]{2,6}-[0-9]{1,6})"
            match = re.findall(regex, "${{ github.ref_name }}")
            print(${{ github.event.pull_request.title }})

            for item in match:
              print(item)